#!/usr/bin/env python

from dag import gsub
import dag

def print_usage():
    print("Usage: gsub [options] <filename>")
    print("Options:")
    print("-d, --dagfile FILE\tSpecify DAG file to be used. Default: jobs.dag")
    print("-i, --init FILE\t\tSpecify input file to be used. Default: $HOME/.boincdag")
    print("-s, --setup_only\t\tSetup the DAG, but do not stage and run jobs. Default: off")
    print("-v, --version\t\tPrint version info.")
    
if __name__ == "__main__":
    from sys import argv
    from getopt import getopt

    init_filename = None
    dagfilename = dag.DEFAULT_DAGFILE_NAME
    start_jobs = True
    
    (optlist,args) = getopt(argv[1:],'d:hi:sv',['dagfile=','help','init=','setup_only','version'])

    for (opt,val) in optlist:
        while opt[0] == '-':
            opt = opt[1:]
        if opt in ['d','dagfile']:
            dagfilename = val
        elif opt in ["h","help"]:
            print_usage()
            exit(0)
        elif opt in ['i',"init"]:
            init_filename = val
        elif opt in ['s','setup_only']:
            start_jobs = False
        elif opt in ['v','version']:
            print("0.0")
            exit(0)
        else:
            from sys import stderr
            stderr.write("Unknown option '%s'\n" % opt)
            exit(1)


    if len(args) == 0:
        print_usage()
        exit(1)
        
    if gsub.gsub(args[0],start_jobs,dagfilename,init_filename) == None:
        exit(1)
