#!/usr/bin/env python

from dag.update_dag import update_dag
import dag

def print_help(command = None):
    import dag.update_dag as UD
    commands = UD.command_help.keys()
    if not command:
        from sys import argv
        import os.path as OP
        print("Usage: %s <cmd> [args]" % OP.basename(argv[0]))
        print("")
        print("Commands are %s" % ", ".join(commands))
        return

    UD.print_help(command)

if __name__ == "__main__":
    from sys import argv
    from getopt import getopt

    debug = False
    
    dagfile = dag.DEFAULT_DAGFILE_NAME

    
    (optlist,args) = getopt(argv[1:],'d:h',['dagfile=',"debug","help"])

    if not args:
        print_help()
        exit(1)

    for (opt,optarg) in optlist:
        while opt[0] == '-':
            opt = opt[1:]
        if opt in ["d", "dagfile"]:
            dagfile = optarg
        elif opt == "debug":
            debug = True
        elif opt in ["h","help"]:
            print_help(optarg)
        else:
            print("Unknown option: '%s'" % optlist)
            exit(1)

    try:
        update_dag(args[0],args[1:],dagfile, debug)
    except Exception as e:
        import traceback
        if debug:
            traceback.print_exc()
        else:
            print("Error running '%s'" % args[0])
            print("Message: {0}".format(e.message))
            exit(1)
