#!/usr/bin/env python

from dag.update_dag import update_dag
import dag

def print_help(command = None):
    import dag.update_dag as UD
    commands = UD.command_help.keys()
    if not command:
        from sys import argv
        import os.path as OP
        print("Usage: %s <cmd> [args]" % OP.basename(argv[0]))
        print("")
        print("Commands are %s" % ", ".join(commands))
        return

    UD.print_help(command)
    
if __name__ == "__main__":
    from sys import argv
    from getopt import getopt

    debug = False
    num_cores = None
    dagfile = dag.DEFAULT_DAGFILE_NAME
    init_filename = None

    if "--version" in argv or "-version" in argv:
        print(dag.__version__)
        exit(0)

    (optlist,args) = getopt(argv[1:],'d:hi:n:',['init=', 'cores=','dagfile=',"debug","help"])

    if not args:
        print_help()
        exit(1)

    for (opt, optarg) in optlist:
        while opt[0] == '-':
            opt = opt[1:]
        if opt in ["n", "cores"]:
            num_cores = int(optarg)
        elif opt in ["d", "dagfile"]:
            dagfile = optarg
        elif opt == "debug":
            import logging
            logger = logging.getLogger('dag')
            logger.setLevel(logging.DEBUG)
            fh = logging.FileHandler(optarg)
            fh.setLevel(logging.DEBUG)
            logger.addHandler(fh)
            debug = True
        elif opt in ["h","help"]:
            print_help(optarg)
        elif opt in ['i', 'init']:
            init_filename = optarg
        else:
            print("Unknown option: '%s'" % optlist)
            exit(1)

    # Init file
    init_file = None
    if init_filename:
        try:
            init_file = open(init_filename, "r")
        except IOError as ioe:
            errmsg = "Could not read init file '%s'\n" % init_filename
            if hasattr(ioe, "errno") and hasattr(ioe, "stderr"):
                errmsg += "Reason{0}: {1}\n".format(ioe.errno, ioe.stderr)
            raise dag.DagException(errmsg)
    else:
        from dag.util import open_user_init
        init_file = open_user_init()

    try:
        update_dag(args[0],args[1:],dagfile, debug, num_cores, init_file=init_file)
    except Exception as e:
        import traceback
        if debug:
            traceback.print_exc()
        else:
            print("Error running '%s'" % args[0])
            print("Message: {0}".format(e.message))
            exit(1)
